language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.5"
  - "3.6"
cache: pip
addons:
  apt:
    sources:  ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      # - ubuntu-toolchain-r-test
      # - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - gcc-6
      - g++-6
      - cmake
      - cmake-data
      - libhdf5-serial-dev
      - hdf5-tools
      - python-numpy
      - python-scipy
      - libprotoc-dev
install:
  - pip install -r python/requirements.txt
  - pip install -r python/setup_requirements.txt
  - pip install -r python/test_requirements.txt

script: 
  - cmake .
  - make -j8
  - make pytest
